Umple build
umple/umple.gradle pull request #6
Opened 2017-02-24 23:33 UTC by AdamBJ

- Added constants for property value names to make them easier to view and change
- Added default values for plugin configuration properties
- Added `addGeneratedToSource` that adds the generated Java files to the `generatedSource` source set. This source set is used when it's time compile the Java code

2017-02-24 23:35 UTC, AdamBJ commented
Hi guys,

If you want to try out these changes locally, remember that you'll need to build the plugin locally and then point the `build.umple` file belonging to the project you want to apply the plugin to at the plugin jar. Merging this PR will not update the version of the Umple plugin on the Gradle plugin portal.

2017-02-25 01:55 UTC, Nava2 requested changes
How do we actually run this then?

2017-02-25 01:55 UTC, Nava2 commented on src/main/groovy/cruise/umple/UmpleGradlePlugin.groovy
> +		m_languageToGenerate = 'Java'
Please make these constants.

2017-02-25 02:00 UTC, AdamBJ commented
@Nava2 I'll post a sample build file in the issue tracker. You just need to change where Gradle looks for the umple jar

2017-02-25 02:57 UTC, AdamBJ commented on src/main/groovy/cruise/umple/UmpleGradlePlugin.groovy
> +		m_languageToGenerate = 'Java'
I've check in changes, please have a look

2017-02-25 16:21 UTC, Nava2 approved these changes

2017-02-25 19:27 UTC, merged